groups:
- name: predictive-maintenance
  rules:
  # Alarmas para componentes del sistema
  - alert: ServiceDown
    expr: up{job="predictive-services"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Servicio caído: {{ $labels.instance }}"
      description: "El servicio {{ $labels.instance }} está caído por más de 1 minuto."

  - alert: HighCPUUsage
    expr: rate(process_cpu_seconds_total{job="predictive-services"}[5m]) * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Alto uso de CPU: {{ $labels.instance }}"
      description: "El servicio {{ $labels.instance }} tiene un uso de CPU superior al 80% por más de 5 minutos: {{ $value }}%"

  - alert: HighMemoryUsage
    expr: process_resident_memory_bytes{job="predictive-services"} / 1024 / 1024 / 1024 > 1.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Alto uso de memoria: {{ $labels.instance }}"
      description: "El servicio {{ $labels.instance }} está utilizando más de 1.5GB de memoria: {{ $value | humanize }}GB"

  # Alarmas específicas para detectores de anomalías
  - alert: HighAnomalyRate
    expr: rate(predictive_anomaly_detected_total[15m]) > 10
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Alta tasa de anomalías detectadas"
      description: "Se han detectado más de 10 anomalías en los últimos 15 minutos."

  - alert: LowPredictionAccuracy
    expr: predictive_prediction_accuracy < 0.7
    for: 1h
    labels:
      severity: warning
    annotations:
      summary: "Baja precisión en predicciones: {{ $labels.service_id }}"
      description: "La precisión de las predicciones para {{ $labels.service_id }} ha caído por debajo del 70%: {{ $value | humanize }}%"

  - alert: ActionExecutionFailures
    expr: rate(predictive_action_executed_total{result="failure"}[15m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Fallos en ejecución de acciones: {{ $labels.service_id }}"
      description: "La acción {{ $labels.action_id }} para {{ $labels.service_id }} está fallando."

  # Alarmas para servicios monitoreados
  - alert: HighServiceResponseTime
    expr: service_response_time_ms_avg > 500
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Tiempo de respuesta alto: {{ $labels.service_id }}"
      description: "El servicio {{ $labels.service_id }} tiene un tiempo de respuesta superior a 500ms durante los últimos 5 minutos: {{ $value }}ms"

  - alert: HighServiceErrorRate
    expr: service_error_rate > 0.05
    for: 3m
    labels:
      severity: critical
    annotations:
      summary: "Alta tasa de errores: {{ $labels.service_id }}"
      description: "El servicio {{ $labels.service_id }} tiene una tasa de errores superior al 5% durante los últimos 3 minutos: {{ $value | humanize }}%"

  - alert: LowServiceAvailability
    expr: service_availability < 0.95
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Baja disponibilidad: {{ $labels.service_id }}"
      description: "El servicio {{ $labels.service_id }} tiene una disponibilidad inferior al 95% durante los últimos 5 minutos: {{ $value | humanize }}%"

  # Alarmas para bases de datos
  - alert: HighDatabaseConnections
    expr: database_active_connections > 100
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Muchas conexiones de base de datos: {{ $labels.service_id }}"
      description: "La base de datos {{ $labels.service_id }} tiene más de 100 conexiones activas durante los últimos 10 minutos: {{ $value }}"

  - alert: SlowDatabaseQueries
    expr: database_query_time_ms_avg > 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Consultas lentas en base de datos: {{ $labels.service_id }}"
      description: "La base de datos {{ $labels.service_id }} tiene consultas con tiempo promedio superior a 1 segundo: {{ $value }}ms"