global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
    - targets: ['pushgateway:9091']

  - job_name: 'predictive-services'
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
    - targets: ['api:8000', 'anomaly-detector:8080', 'predictive-engine:8080', 'action-recommender:8080', 'service-profiler:8080']
